extract = '(total_dyn_inst: (\d+))'
benchmarks = '../int-benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.ssa]
pipeline = [
    "bril2json",
    "python ../ssa.py --to-ssa=True",
    "brili -p {args}",
]