extract = 'total_dyn_inst: (\d+)'
benchmarks = '../int-benchmarks/*.bril'
timeout = 60

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.licm]
pipeline = [
    "bril2json",
    "python3 ../dce.py",
    "brili -p {args}",
]