extract = 'total_dyn_inst: (\d+)'
benchmarks = '../all-benchmarks/*.bril'
timeout = 60

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.inline]
pipeline = [
    "bril2json",
    "python3 ../inlining.py",
    "brili -p {args}",
]