extract = 'total_dyn_inst: (\d+)'
benchmarks = '../all-benchmarks/*.bril'
timeout = 60

[runs.baseline]
pipeline = [
    "bril2json",
    "brili-vc -p {args}",
]

[runs.oplvn]
pipeline = [
    "bril2json",
    "python3 ../naive_vectorization.py",
    "brili-vc -p {args}",
]