extract = 'total_dyn_inst: (\d+)'
benchmarks = '../all-benchmarks/*.bril'
timeout = 60

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.storemovement]
pipeline = [
    "bril2json",
    "python3 ../store_movement.py",
    "brili -p {args}",
]