extract = 'total_dyn_inst: (\d+)'
benchmarks = '../all-benchmarks/*.bril'
timeout = 60

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.trace]
pipeline = [
    "bril2json",
    "brili-tr {args}",
    "python3 ../trace.py",
    "brili -p {args}",
]