extract = 'total_vectors_created: (\d+)'
benchmarks = '../all-benchmarks/*.bril'
timeout = 60

[runs.baseline]
pipeline = [
    "bril2json",
    "brili-vc -v {args}",
]

[runs.op]
pipeline = [
    "bril2json",
    "python3 ../vectorization.py --op=True",
    "brili-vc -v {args}",
]

[runs.naive]
pipeline = [
    "bril2json",
    "python3 ../vectorization.py --naive=True",
    "brili-vc -v {args}",
]